Feat/info card comp
Sevaarth/sevaarth pull request #78
Opened 2024-09-24 18:07 UTC by Dhanjeet09

2024-09-24 18:09 UTC, imohitmehto approved these changes
Approving without looking into code so please do testing on dev server  properly

2024-09-24 18:10 UTC, imohitmehto requested changes
Change target branch from main to dev

2024-09-24 18:12 UTC, imohitmehto commented
Changing target branch from main to dev

2024-09-24 18:14 UTC, imohitmehto approved these changes, later dismissed

2024-09-25 06:56 UTC, rai-09 approved these changes, later dismissed

2024-09-25 07:32 UTC, rai-09 submitted a review, later dismissed

2024-09-25 07:33 UTC, rai-09 approved these changes

2024-09-25 07:35 UTC, merged